ignore Spree::Calculator::PerItem error
Spree::Calculator::PerItem has since been removed in 2.2.stable so the migration 20140309023735_migrate_old_preferences throws an error:
NameError: uninitialized constant Spree::Calculator::PerItem
Wrapping it in a rescue block will be fine.

Please refer to https://github.com/spree/spree/issues/4274 which is the same issue.